// This file is generated by kconfig_compiler_kf5 from options.kcfg.
// All changes you do to this file will be lost.
#ifndef FOCUSTRACKCONFIG_H
#define FOCUSTRACKCONFIG_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class FocusTrackConfig : public KConfigSkeleton
{
  public:

    static FocusTrackConfig *self();
    ~FocusTrackConfig() override;

    /**
      Set borderColor
    */
    static
    void setBorderColor( uint v )
    {
      if (!self()->isBorderColorImmutable())
        self()->mBorderColor = v;
    }

    /**
      Get borderColor
    */
    static
    uint borderColor()
    {
      return self()->mBorderColor;
    }

    /**
      Is borderColor Immutable
    */
    static
    bool isBorderColorImmutable()
    {
      return self()->isImmutable( QStringLiteral( "borderColor" ) );
    }

    /**
      Set borderWidth
    */
    static
    void setBorderWidth( uint v )
    {
      if (!self()->isBorderWidthImmutable())
        self()->mBorderWidth = v;
    }

    /**
      Get borderWidth
    */
    static
    uint borderWidth()
    {
      return self()->mBorderWidth;
    }

    /**
      Is borderWidth Immutable
    */
    static
    bool isBorderWidthImmutable()
    {
      return self()->isImmutable( QStringLiteral( "borderWidth" ) );
    }

  protected:
    FocusTrackConfig();
    friend class FocusTrackConfigHelper;


    // Effect-ًFocusTrack
    uint mBorderColor;
    uint mBorderWidth;

  private:
};

#endif

